"project_identifier_env" : CROWDIN_PROJECT_ID
"api_key_env" : CROWDIN_API_KEY
"base_path" : "."

"preserve_hierarchy": false

files: [
 {
  "source" : "/translations/messages.json",
  "translation" : "/translations/messages.%locale%.%file_extension%",
  "languages_mapping" : {
    "locale" : {
      "en-US": "en_US",
      "es-ES": "es",
      "zh-CN": "zh",
      "zh-HK": "zh_HK",
      "pt-BR": "pt",
      "de": "de",
      "el": "el",
      "et": "et",
      "fr": "fr",
      "hu": "hu",
      "it": "it",
      "ja": "ja",
      "ko": "ko",
      "pl": "pl",
      "ro": "ro",
      "ru": "ru",
      "en-GB": "en",
      "es-MX": "es_MX",
      "tr": "tr"
    }
  },
  "update_option" : "update_as_unapproved"
 }
]
