defaults: &defaults
  working_directory: ~/public-navigation
  docker:
    - image: circleci/node:latest
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/public-navigation
      - run:
          name: Test
          command: npm test
  push-and-pull-translations:
    working_directory: ~/public-navigation
    docker:
      - image: circleci/java:latest
    steps:
      - attach_workspace:
          at: ~/public-navigation
      - run:
          name: Download CrowdIn CLI
          command: |
            wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
            sudo dpkg -i crowdin.deb
      - run:
          name: Replace slash with period in branch name for CrowdIn
          command: |
            echo 'export CROWDIN_BRANCH=${CIRCLE_BRANCH//\//.}' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Push translations
          command: echo ${CROWDIN_BRANCH} && crowdin push -b ${CROWDIN_BRANCH}
      - run:
          name: Pull translations
          command: crowdin pull -b ${CROWDIN_BRANCH}
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy-docs-to-root:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/public-navigation
      - run:
          name: Build docs
          command: npm run build-docs
      - run:
          name: Deploy docs
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-docs-to-dir .
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy-docs-for-branch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/public-navigation
      - run:
          name: Build docs
          command: npm run build-docs
      - run:
          name: Deploy docs
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-docs-for-branch
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/public-navigation
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            npm run release-to-github
      - run:
          name: Publish on npm
          command: npm publish --access=public

workflows:
  version: 2
  build-test-release-and-build-docs:
    jobs:
      - build
      - push-and-pull-translations:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy-docs-to-root:
          requires:
            - test
            - push-and-pull-translations
          filters:
            branches:
              only: master
      - deploy-docs-for-branch:
          requires:
            - test
            - push-and-pull-translations
          filters:
            branches:
              ignore:
                - master
      - release:
          context: frontend-publish
          requires:
            - deploy-docs-to-root
          filters:
            branches:
              only: master